### ISSUE TITLE
Question regarding the use of ref peaks in your paper.

### ISSUE THREAD

**Issue by YonghuiDong** [Vitek-Lab/Cardinal3-vignettes#1]
Hi,

Many thanks for the detailed workflow described in vignette. I have a question regarding your workflow, thanks for your help.

As shown in the script below, you first get the spectrum `mse_mean`, and use the `use_mean` to calculate the reference peaks. Since `mse_mean` is already a single pixel imaging dataset (i.e., a single spectrum), why do you need to perform `peakAlign` and `peakFilter`? I don't see the logic here. There are no addition spectra to align with, and all the m/z features in `mse_mean` are unique, and how can we filter them based on the peak occuring frequency? 

```r
mse_mean <- summarizeFeatures(mse, FUN="mean")

ref <- mse_mean %>%
	peakPick(method="mad", SNR=6) %>%
	peakAlign("mean", tolerance=15, units="ppm") %>%
	peakFilter() %>%
	process()
```

Thanks again for your help.

Dong

**Comment by kuwisdelu** [comment]
They are essentially there just to put the data in the expected format. On its own peakPick() does not reduce the dataset to the peaks it has found. The following function calls are just there to set up the new m/z features (peaks), remove the rest of the non-peak m/z features, and properly mark the dataset as consisting only of centroided peaks. They are really doing any useful spectral processing in this case, just restructuring the object.
